#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'rpmforge', 
  :git => 'git://github.com/xforty/chef-rpmforge.git',
 :ref => 'master'



cookbook 'database', '1.1.0'
cookbook 'postgresql', '0.99.2'

cookbook 'apache2', 
  :git => 'git@github.com:francescoagati/apache2.git',
 :ref => 'master'


# Load HEAD of master branch until we tag an intial release
cookbook 'initdb',
  :git => 'git://github.com/xforty/chef-initdb.git',
  :ref => 'master'

# Load HEAD of master branch until we tag an intial release
cookbook 'xforty',
  :git => 'git://github.com/xforty/chef-xforty.git',
  :ref => 'master'

cookbook 'rvm',
  :git => 'git://github.com/fnichol/chef-rvm.git',
  :ref => 'master'

# Load from xforty repo until known issue is fixed
# https://github.com/opscode/cookbooks/pull/286
cookbook 'mysql',
  :git => 'git://github.com/xforty/cookbooks.git',
  :ref => 'master',
  :path => 'mysql'
